### ISSUE TITLE
SVG optimisation

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/assets.ubuntu.com#78]
Please remove comments from optimised SVG's.

For example, check the source of https://assets.ubuntu.com/v1/7e21b535-logo-juju.svg contains:
`<!-- Generator: Adobe Illustrator 17.0.2, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->`

**Comment by nottrobin** [comment]
Unless I'm missing something, I don't think this is worth doing. It would save so little in terms of filesize, and I'm not aware of it breaking anything or being regularly causing any errors or warnings.

I'm closing this for now. If you disagree, please explain why you think it's important.
